services:
  nats:
    image: nats:latest
    command: -c /etc/nats/nats.conf
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
      - "443:443"
    volumes:
       - ./configs/nats/:/etc/nats/

  io:
    image: natsio/nats-box:latest
    entrypoint:
      - /bin/sh
    tty: true
    depends_on:
      - nats

  cmd:
    image: foliage-demo/cmd:latest
    restart: always
    command: /usr/bin/runtime -ll 6
    env_file: ./configs/.env
    depends_on:
      - nats
    build:
      context: ..
      dockerfile: m2/cmd/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cmd:9000/health"]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - ./cmd/data:/data
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    stop_grace_period: 1m

  cn-ad_m2_k8s:
    image: foliage-demo/cn-ad-k8s:latest
    restart: always
    command: /usr/bin/runtime -ll 6
    env_file: ./configs/.env
    depends_on:
      cmd:
        condition: service_healthy
    volumes:
      - ./configs/kubeconfig:/configs/kubeconfig
    build:
      context: ..
      dockerfile: m2/cn_ad/k8s/Dockerfile
    logging:
      options:
        max-size: "10m"
        max-file: "5"
