services:
  nats:
    image: nats:latest
    command: -c /etc/nats.conf
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
      - "443:443"
    volumes:
       - ./nats.conf:/etc/nats.conf

  cmd:
    image: foliage-demo/cmd-m2:latest
    restart: always
    command: /usr/bin/runtime -ll 6
    env_file: cmd/.env
    depends_on:
      - nats
    build:
      context: ..
      dockerfile: m2/cmd/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cmd:9000/health"]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - ./cmd/data:/data
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    stop_grace_period: 1m

  cn-ad_k8s:
    image: foliage-demo/cn-ad-k8s:latest
    restart: always
    command: /usr/bin/runtime -ll 6
    env_file: cn_ad/k8s/.env
    depends_on:
      cmd:
        condition: service_healthy
    volumes:
      - ./kubeconfig:/kubeconfig:ro
      - ./dumps/:/dumps/
    build:
      context: ..
      dockerfile: m2/cn_ad/k8s/Dockerfile
    logging:
      options:
        max-size: "10m"
        max-file: "5"
