port: 4222
http_port: 8222
max_payload: 16MB
websocket: {
    port: 443
    no_tls: true
}
jetstream {
    store_dir: /data/jetstream
    domain: "m2"
}
leafnodes {
    remotes [
        { url: "nats://nats:foliage@nats:7422" }
    ]}
authorization {
    users = [
        {
            user: "nats"
            password: "foliage"
        }
    ]
}