name: Control docker compose (no cleanup)

on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        options: [m1, m2, m3, m4]
      action:
        type: choice
        options: [start, stop, restart]

jobs:
  control:
    runs-on: self-hosted

    steps:
      - name: Control compose
        run: |
          cd ${{ github.event.inputs.module }}

          case "${{ github.event.inputs.action }}" in
            start)
              docker compose start
              ;;
            stop)
              docker compose stop
              ;;
            restart)
              docker compose restart
              ;;
          esac
