name: Deploy m4

on:
  push:
    branches: [ dev ]
    paths:
      - 'm4/**'

jobs:
  deploy:
    runs-on: [self-hosted, m4]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd m4
          docker compose build  

      - name: Stop and cleanup
        run: |
          docker compose -p m4 -f m4/docker-compose.yaml down -v --remove-orphans

      - name: Deploy m4
        run: |
          cd m4
          docker compose up -d

